services:
  mason-dev:
    build: .
    container_name: mason-dev
    restart: unless-stopped
    networks:
      - backend_net
    volumes:
      - ./app:/app
    command: fastapi dev app.py --host 0.0.0.0 --port 8002

networks:
  backend_net:
    external: true
