import { api } from "./APIController";
import { APIKeysController } from "./APIKeysController";
import type { ConfigModel } from "./Models";
import { SignupController } from "./SignupController";

export class ConfigController{
    public config?: ConfigModel
    public apiKeys = new APIKeysController("ConfigFlow");
    public signup = new SignupController();
    /**
     * Checks the provided CONFIG_KEY with the one generated by the container.
     * 
     * @param key provided CONFIG_KEY
     * @returns `true` if valid, `false` otherwise
     */
    public async checkKey(key: string){
        try{
            const data = await api.request("/api/public/auth/validate_config_key", {
                method: "POST",
                headers: {
                    "Content-Type": "Application/json"
                },
                body: JSON.stringify({
                    key: key
                })
            })

            return data;
        } catch(e){
            return false;
        }
    }
    
    public async getConfig(){
        try{
            const data = await api.request("/api/public/config/get");

            this.config = data;
        } catch(e){
            this.config = undefined;
        }
    }

    public async saveConfig(form: HTMLFormElement){
        try{
            await api.request("/api/admin/config/update", {
                method: "PUT",
                body: new FormData(form)
            })
        } catch(e){
            console.error(e);
        }
    }
}